Repository Schniz/gpkg, pull requests merged in 2021-09, with the labels that each got.

#33 add miette for error printing
  Cargo.lock
  gpkg/Cargo.toml
  gpkg/src/from.rs
  gpkg/src/install_package.rs
  gpkg/src/lib.rs
  gpkg_cli/Cargo.toml
  gpkg_cli/src/cli.rs
  gpkg_cli/src/commands/command.rs
  gpkg_cli/src/commands/completions.rs
  gpkg_cli/src/commands/install.rs
  gpkg_cli/src/commands/list.rs
  gpkg_cli/src/commands/uninstall.rs
  gpkg_cli/src/main.rs
Labels: PR: New Feature

#34 Support for stringified binary field
  gpkg/src/install_package.rs
Labels: PR: Bugfix

#35 Fix GH actions
  .github/workflows/rust.yml
  gpkg/src/install_package.rs
  gpkg/src/node_package_version.rs
  gpkg_cli/src/commands/uninstall.rs
  gpkg_cli/src/main.rs
Labels: PR: Internal
